### ISSUE TITLE
A error in part - 5 of the series

### ISSUE THREAD

**Issue by V1nay90** [Carberra/updated-discord.py-tutorial#6]
Error:
```python
Traceback (most recent call last):
  File "launcher.py", line 1, in <module>
    from lib.bot import bot
  File "path/__init.py__", line 7, in <module>
    class Bot(BotBase):
TypeError: module() takes at most 2 arguments (3 given)
```
code:
```python
class Bot(BotBase):
    def __init__(self):
        self.PREFIX = PREFIX
        self.ready = False
        self.guild = None
        self.scheduler = AsyncIOScheduler()

        super().__init__(command_prefix = PREFIX, owner_ids = OWNER_ID)
```

**Comment by parafoxia** [comment]
Please ask your question in the support server; the GitHub repo should not be used as a support channel.
